[package]
disabled = true

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"

[nodejs]
disabled = true

[python]
disabled = true

[ruby]
disabled = true

[git_branch]
symbol = ""
